-- SmartDrive customer feedback schema.
-- Run this in the Supabase SQL Editor once.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null check (char_length(trim(customer_name)) between 1 and 120),
  customer_email text not null default '' check (char_length(customer_email) <= 254),
  rating smallint not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 1000),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists reviews_created_at_idx
  on public.reviews (created_at desc);

create index if not exists reviews_user_id_idx
  on public.reviews (user_id);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
  on public.reviews
  for select
  using (true);

drop policy if exists "Authenticated users can submit reviews" on public.reviews;
create policy "Authenticated users can submit reviews"
  on public.reviews
  for insert
  to authenticated
  with check (user_id is null or user_id = (select auth.uid()));

-- The web dashboard can submit an anonymous review when no Supabase session
-- is available. It cannot impersonate an authenticated user.
drop policy if exists "Guests can submit anonymous reviews" on public.reviews;
create policy "Guests can submit anonymous reviews"
  on public.reviews
  for insert
  to anon
  with check (user_id is null);

revoke update, delete on public.reviews from anon, authenticated;
grant select on public.reviews to anon, authenticated;
grant insert on public.reviews to anon, authenticated;
